export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const SET_CONTRACT_START = 'SET_CONTRACT_START'
export const SET_CONTRACT_SUCCESS = 'SET_CONTRACT_SUCCESS'
export const SET_CONTRACT_FAIL = 'SET_CONTRACT_FAIL'

export const FETCH_CONTRACTS_START = 'FETCH_CONTRACT_START'
export const FETCH_CONTRACTS_SUCCESS = 'FETCH_CONTRACTS_SUCCESS'
export const FETCH_CONTRACTS_FAIL = 'FETCH_CONTRACT_FAIL'
export const EDIT_CONTRACT = 'EDIT_CONTRACT'
